# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('sex', models.BooleanField(default=1)),
                ('icons', models.ImageField(upload_to='icons')),
                ('isdelete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'axf_usermodel',
            },
        ),
    ]
